### ISSUE TITLE
Standardize documentation and require SHELL to be passed in

### ISSUE THREAD

**Issue by zph** [toumorokoshi/tome#12]
ah ok, I see what you did. It sounds like you're planning on switching to always passing in a shell argument which is good. If you want to merge this in and address that in a future PR, that's fine too.

_Originally posted by @toumorokoshi in https://github.com/toumorokoshi/tome/pull/4#r601986949_

**Comment by toumorokoshi** [comment]
I forgot precisely what this was, so we can close out for now.
