### ISSUE TITLE
Python script doesn't receive args

### ISSUE THREAD

**Issue by hilkins** [toumorokoshi/tome#16]
I'm switching from sub to tome to take advantage of the nesting (e.g. my-command nested nested cmd) but it seems that scripts doesn't receive the arguments passed when calling the tome instance.

I have this setup:

.zshrc
```zsh
eval "$(tome init my-tome ~/my-scripts zsh)"
```
~/my-scripts/python-test
```python
#!/usr/bin/env python
import sys

print(sys.argv)
```

When I run the script through tome I get:
```sh
▶ my-tome python-test 1 2 3 4
['/home/hwbb/my-scripts/python-test']
```

Instead of:
```sh
▶ my-tome python-test 1 2 3 4
['/home/hwbb/my-scripts/python-test', '1', '2', '3', '4']
```

**Comment by hilkins** [comment]
Hey @toumorokoshi, any news on this ?

I've tried again and it does work properly with source scripts.

~/my-scripts/source-test
```bash
# SOURCE
echo $*
```

```
▶ my-tome source-test 1 2 3 4
1 2 3 4
```

**Comment by toumorokoshi** [comment]
> Hey @toumorokoshi, any news on this ?

Sorry about that!

I found the bug, it was [pretty straightforward](https://github.com/toumorokoshi/tome/commit/356710fbe811c673d88a1da7922e2f2644a2ea4f). Doh!

I'll work on getting a release out. Unfortunately I no longer have access to a Mac, so that may slow the release for OSX, but I'm working on it.

**Comment by toumorokoshi** [comment]
So I have a [release on 0.7.3](https://github.com/toumorokoshi/tome/releases/tag/v0.7.3). Unfortunately I was only able to compile Linux.

I have an OSX machine on the way but that'll probably take a week. Apologies about that. Rust is pretty easy to build locally if you find you can't wait.

**Comment by hilkins** [comment]
Thanks a lot, it's working properly now :)
