### ISSUE TITLE
Design Discussion: how to handle tab completion?

### ISSUE THREAD

**Issue by toumorokoshi** [toumorokoshi/tome#19]
As tome is moving to 1.0, one particular design that could be improved is tab completion. Consider this a request for comments or design.

Today, tome provides some primitive support for tab completion, by running the script with the `--complete` argument and expecting a list of strings with the possible candidates when a user attempts to tab-complete on a  terminal command.

This works fine, but doesn't allow for more complex completion semantics such as those offered by [zsh](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#telling-zsh-which-function-to-use-for-completing-a-command). 

From a design standpoint, it would be great to just enable support for various shell's completion without offering first-class functionality for any specific one. 

I haven't read too deeply on this topic myself, so I'm curious if there's suggestions from others who use tome.

**Comment by toumorokoshi** [comment]
@zph since you offered to give input on ideas :)

**Comment by zph** [comment]
I leveraged clap.rs for the commandline shell completions across multiple shells (bash, fish, zsh) in the fork experiment here: https://github.com/zph/tome/blob/use-clap/src/main.rs#L82-L87 and https://github.com/zph/tome/blob/use-clap/src/commands/init.rs#L284-L306.

The library code is here: https://github.com/clap-rs/clap/tree/master/clap_generate. I remember having to use an RC version of it but clap just hit v3.0 so should have included the changes I needed.

If that approach is desirable, you or we could harvest from my fork for a starting point. I believe the branch I was using was `use-clap` in my fork.

**Comment by toumorokoshi** [comment]
Thanks! investigation showed that completion mechanisms are not that complex, so the system as is works great.

Closing as won't fix.
