### ISSUE TITLE
Directory-Based Autocompletion

### ISSUE THREAD

**Issue by bmeynell** [toumorokoshi/tome#2]
**Environment**:
```
# ... using latest tome macos binary

$ /usr/bin/env bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)

$ echo $SHELL && echo $BASH
/bin/bash
/bin/bash

# ... (also tried on Kali Linux, latest w/tome linux binary)
```

**Bash Init**:
```
eval "`~/.local/bin/tome init clinja /scripts $0`"
```

**Scripts**:
```
/scripts
$ tree
.
└── create-app
    ├── api
    └── console

1 directory, 2 files

# directory: `create-app`
# files: `api`, `console`
```

**File Content**:

**api**:
```
 $ cat create-app/api
#!/usr/bin/env bash
echo "creating api app!"
```

**console**:
```
 $ cat create-app/console
#!/usr/bin/env bash
echo "creating console app!"
```

**Expected**:

```
# fluid autocompletion
clinja create-app api
creating api app!
```

**Actual**:
```
 $  clinja
This is an instance of tome, running against the directory /scripts.
The commands are namespaced by the directory structure.
Full list of commands available are:
 create-app api:
 create-app console:

# `create-app` _does_ autocomplete (expected)
# however, `create-app` repeats whenever tab is invoked (unexpected)
$  clinja create-app create-app create-app

# `api` must be _manually_ entered, instead of relying on autocomplete (expected), which renders the expected output
$  clinja create-app api
creating api app!
```

User Error?

**Comment by toumorokoshi** [comment]
Sorry for the super delayed response! 

Sounds like a bug. I'll take a closer look. Also #3 may yield quite a few ergonomic improvements with Tome, which may resolve the bug along the way.

I'll take a look and round back.

**Comment by zph** [comment]
I tried to reproduce this bug and failed :(. But, there's a possibility we can autogenerate almost all our cli completion code thanks to discussion in #3.

If we can't easily reproduce it, let's see what happens with #3's Batch #2 approach 👯 with the expectation it will likely address any remaining but hard to reproduce issue.

**Comment by toumorokoshi** [comment]
@bmeynell after a long delay, I'm finally getting bandwidth to investigate these issues.

I tried to reproduce but I was unsuccessful as well. Can you see if this happens with the latest binary (0.7.5), or is still relevant? I know OSX now defaults to zsh.

**Comment by toumorokoshi** [comment]
will close for now, thanks! feel free to comment if this should be re-opened.
