### ISSUE TITLE
wish: improve experience for running without shell `init`

### ISSUE THREAD

**Issue by markstos** [toumorokoshi/tome#40]
I'm a long-time `sub` user and run the resulting scripts on servers as well as my laptop. In a server context, I think running an `init` function against the shell first could be awkward or error prone. 

I would like a convenient way to run scripts in a server context without `init`. It can be done now, but the syntax is awkward:

```
eval (tome command-execute path/to/scripts/ -s fish -- my-command)
```

It looks like the reason that `eval` is used here is to allow completion to work, which isn't necessary for server/scripting use. Also, maybe passing the  shell is not required either if completion doesn't need to be supported. So something like this could made to work:

```
tome run  path/to/scripts/ -- my-command
```

But that's still a bit unintuitive if you are used to calling the command by it's custom name and not as `tome`. 

So another alternative is to supply an option to print out script which would not support completion, but would simply one line of bash:

```
my-command tome script>~/project/bin/my-command
```

Now `~/project/bin/my-command` can be checked into Git and would  work just like the function, but without the completion support.  From here, `~/project/bin/my-command` can be used on deployments without further initialization.

But maybe I'm missing the obvious and on the server the scripts could just be called directly, without using tome at all--- that would actually be  nice to not have one more dependency on package which requires manual installation. This would be OK as long as the scripts don't call each user using the custom command name. In this case, I guess what would be really beneficial is a simple shell-script version of the tool that doesn't support completion just handles executing the scripts.

**Comment by toumorokoshi** [comment]
Thanks for the issue! I've also used sub heavily as well and hopefully tome can help for some more advanced cases.

Overall I'm supportive of tome being useful in more contexts. Some specific thoughts:

I'm a little wary of eliminating the need of the tome binary altogether. My primary concern is that whatever bash script that gets emitted will only be a subset and if more advanced feature are added (better parsing of help for example). 

Architecturally I feel like this could be best accomplished by rewriting the command discovery logic into bash itself so there wasn't a bifurcation between the "tome rust way" and the "bash way" of doing things. 


> eval (tome command-execute path/to/scripts/ -s fish -- my-command)

regarding this: yes, it's to allow completion to work. I could imagine that instead we could have the tome executable do an exec to transform itself into the appropriate subcommand. Maybe an alternate execution mode as you suggested with the `run` syntax.

To start: WDYT? about just adding a `tome run` as you suggested? the bash command should be fairly trivial that point.

**Comment by markstos** [comment]
I would be happy with `tome run`. I manage my servers with Ansible now, and it's pretty easy to automate installing additional software on to them, even if the software is installed directly from Github and not from a package.

**Comment by toumorokoshi** [comment]
> I would be happy with `tome run`. I manage my servers with Ansible now, and it's pretty easy to automate installing additional software on to them, even if the software is installed directly from Github and not from a package.

Sorry for the late reply here.

Ok, sounds like we agree! I'll take a look at refactoring to support a `tome run`.
