### ISSUE TITLE
tome reports wrong version, exposes "echo"

### ISSUE THREAD

**Issue by markstos** [toumorokoshi/tome#49]
Thanks for the new release. However, it seems that the Cargo file is not getting updated during the release process, and it seems that what Tome is using to report its version. So although i downloaded 0.11.0, running `tome` or `tome --version` will report the version as 0.1.0 instead.

Also, the word "echo" is printed out, which appears to a mistake:

![image](https://github.com/toumorokoshi/tome/assets/25829/20fcbd52-759d-4d65-9f23-1b4e1eb7ee41)

**Comment by toumorokoshi** [comment]
thanks for the report! I'll get a release out shortly with the merged commit.
