### ISSUE TITLE
Perform documentation cleanup and consistency pass

### ISSUE THREAD

**Issue by zph** [toumorokoshi/tome#8]
Yes! I think I did that in the later PR.

Ok w/ leaving it as a nit that we address later in a docs cleanup task? If so, I'll add a placeholder issue to make a pass at documentation cleanup when most interface changes have landed.

_Originally posted by @zph in https://github.com/toumorokoshi/tome/pull/4#discussion_r598155847_

**Comment by toumorokoshi** [comment]
making a note here to clean up the main README.md. it's missing some hotlinks, sections should be shuffled, and link to the actual docs at https://tome-scripts.readthedocs.io/en/latest/design-decisions/.

**Comment by toumorokoshi** [comment]
done!
